import type { EtfDefinition, MacroProfile } from "./types";

export const SECTORS = [
  { key: "materials", label: "Basic Materials", color: "#f59e0b" },
  { key: "communication", label: "Communication", color: "#38bdf8" },
  { key: "consumer-cyclical", label: "Consumer Cyclical", color: "#f472b6" },
  { key: "consumer-defensive", label: "Consumer Defensive", color: "#34d399" },
  { key: "energy", label: "Energy", color: "#fb7185" },
  { key: "financial", label: "Financial", color: "#a78bfa" },
  { key: "healthcare", label: "Healthcare", color: "#2dd4bf" },
  { key: "industrials", label: "Industrials", color: "#94a3b8" },
  { key: "real-estate", label: "Real Estate", color: "#c4b5fd" },
  { key: "technology", label: "Technology", color: "#60a5fa" },
  { key: "utilities", label: "Utilities", color: "#fbbf24" },
] as const;

export const MACROS: { key: MacroProfile; label: string; hint: string }[] = [
  { key: "ciclico", label: "Cíclico / Risk-On", hint: "Beta alta" },
  { key: "defensivo", label: "Defensivo / Risk-Off", hint: "Calidad" },
  { key: "sensible", label: "Sensible", hint: "Macro" },
];

export const BENCHMARKS = [
  {
    ticker: "SPY",
    name: "S&P 500",
    fullName: "SPDR S&P 500 ETF Trust",
  },
  {
    ticker: "QQQ",
    name: "Nasdaq 100",
    fullName: "Invesco QQQ Trust",
  },
] as const;

export const ANOMALY_THRESHOLD = 2.5;

export const ETF_CATALOG: EtfDefinition[] = [
  {
    ticker: "XLB",
    name: "Materials Select Sector SPDR Fund",
    shortName: "Materials Sector",
    sector: "Basic Materials",
    sectorKey: "materials",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "XME",
    name: "SPDR S&P Metals & Mining ETF",
    shortName: "Metals & Mining",
    sector: "Basic Materials",
    sectorKey: "materials",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "SLX",
    name: "VanEck Steel ETF",
    shortName: "Steel Industry",
    sector: "Basic Materials",
    sectorKey: "materials",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "GDX",
    name: "VanEck Gold Miners ETF",
    shortName: "Gold Miners",
    sector: "Basic Materials",
    sectorKey: "materials",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "XLC",
    name: "Communication Services Select Sector SPDR Fund",
    shortName: "Communication",
    sector: "Communication",
    sectorKey: "communication",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "FDN",
    name: "First Trust Dow Jones Internet Index Fund",
    shortName: "Internet Index",
    sector: "Communication",
    sectorKey: "communication",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "IYZ",
    name: "iShares U.S. Telecommunications ETF",
    shortName: "Telecom",
    sector: "Communication",
    sectorKey: "communication",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "XLY",
    name: "Consumer Discretionary Select Sector SPDR Fund",
    shortName: "Consumer Disc.",
    sector: "Consumer Cyclical",
    sectorKey: "consumer-cyclical",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "XRT",
    name: "SPDR S&P Retail ETF",
    shortName: "Retail Industry",
    sector: "Consumer Cyclical",
    sectorKey: "consumer-cyclical",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "PEJ",
    name: "Invesco Dynamic Leisure and Entertainment ETF",
    shortName: "Leisure & Ent.",
    sector: "Consumer Cyclical",
    sectorKey: "consumer-cyclical",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "ITB",
    name: "iShares U.S. Home Construction ETF",
    shortName: "Home Construction",
    sector: "Consumer Cyclical",
    sectorKey: "consumer-cyclical",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "IDRV",
    name: "iShares Self-Driving EV and Tech ETF",
    shortName: "EV & Tech",
    sector: "Consumer Cyclical",
    sectorKey: "consumer-cyclical",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "XLP",
    name: "Consumer Staples Select Sector SPDR Fund",
    shortName: "Consumer Staples",
    sector: "Consumer Defensive",
    sectorKey: "consumer-defensive",
    macroProfile: "defensivo",
    theme: "Defensivo",
  },
  {
    ticker: "VEGI",
    name: "iShares MSCI Agriculture Producers ETF",
    shortName: "Agriculture",
    sector: "Consumer Defensive",
    sectorKey: "consumer-defensive",
    macroProfile: "defensivo",
    theme: "Defensivo",
  },
  {
    ticker: "XLE",
    name: "Energy Select Sector SPDR Fund",
    shortName: "Energy Sector",
    sector: "Energy",
    sectorKey: "energy",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "XOP",
    name: "SPDR S&P Oil & Gas Exploration & Production ETF",
    shortName: "Oil Exploration",
    sector: "Energy",
    sectorKey: "energy",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "OIH",
    name: "VanEck Oil Services ETF",
    shortName: "Oil Services",
    sector: "Energy",
    sectorKey: "energy",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "CRAK",
    name: "VanEck Oil Refiners ETF",
    shortName: "Oil Refiners",
    sector: "Energy",
    sectorKey: "energy",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "TAN",
    name: "Invesco Solar ETF",
    shortName: "Solar Energy",
    sector: "Energy",
    sectorKey: "energy",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "PBW",
    name: "Invesco WilderHill Clean Energy ETF",
    shortName: "Clean Energy",
    sector: "Energy",
    sectorKey: "energy",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "XLF",
    name: "Financial Select Sector SPDR Fund",
    shortName: "Financial Sector",
    sector: "Financial",
    sectorKey: "financial",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "KRE",
    name: "SPDR S&P Regional Banking ETF",
    shortName: "Regional Banks",
    sector: "Financial",
    sectorKey: "financial",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "KBE",
    name: "SPDR S&P Bank ETF",
    shortName: "Commercial Banks",
    sector: "Financial",
    sectorKey: "financial",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "XLV",
    name: "Health Care Select Sector SPDR Fund",
    shortName: "Health Care",
    sector: "Healthcare",
    sectorKey: "healthcare",
    macroProfile: "defensivo",
    theme: "Defensivo",
  },
  {
    ticker: "XBI",
    name: "SPDR S&P Biotech ETF",
    shortName: "Biotech Equal",
    sector: "Healthcare",
    sectorKey: "healthcare",
    macroProfile: "defensivo",
    theme: "Defensivo",
  },
  {
    ticker: "IBB",
    name: "iShares Biotechnology ETF",
    shortName: "Biotech Cap",
    sector: "Healthcare",
    sectorKey: "healthcare",
    macroProfile: "defensivo",
    theme: "Defensivo",
  },
  {
    ticker: "IHI",
    name: "iShares U.S. Medical Devices ETF",
    shortName: "Medical Devices",
    sector: "Healthcare",
    sectorKey: "healthcare",
    macroProfile: "defensivo",
    theme: "Defensivo",
  },
  {
    ticker: "XLI",
    name: "Industrial Select Sector SPDR Fund",
    shortName: "Industrial Sector",
    sector: "Industrials",
    sectorKey: "industrials",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "ITA",
    name: "iShares U.S. Aerospace & Defense ETF",
    shortName: "Aerospace & Def.",
    sector: "Industrials",
    sectorKey: "industrials",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "IYT",
    name: "iShares U.S. Transportation ETF",
    shortName: "Transportation",
    sector: "Industrials",
    sectorKey: "industrials",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "BWET",
    name: "Breakwave Tanker Shipping ETF",
    shortName: "Tanker Shipping",
    sector: "Industrials",
    sectorKey: "industrials",
    macroProfile: "sensible",
    theme: "Sensible",
  },
  {
    ticker: "IYR",
    name: "iShares U.S. Real Estate ETF",
    shortName: "Real Estate",
    sector: "Real Estate",
    sectorKey: "real-estate",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "XLK",
    name: "Technology Select Sector SPDR Fund",
    shortName: "Technology Sector",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "SMH",
    name: "VanEck Semiconductor ETF",
    shortName: "Semiconductors",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "IGV",
    name: "iShares Expanded Tech-Software Sector ETF",
    shortName: "Tech Software",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "CIBR",
    name: "First Trust NASDAQ Cybersecurity ETF",
    shortName: "Cybersecurity",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "ROBO",
    name: "Robo Global Robotics and Automation Index ETF",
    shortName: "Robotics & AI",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "BLOK",
    name: "Amplify Blockchain Technology ETF",
    shortName: "Data & Crypto",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "NCLD",
    name: "Roundhill Neocloud ETF",
    shortName: "Cloud Computing",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "DRAM",
    name: "Roundhill Memory ETF",
    shortName: "Memory Storage",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "LYTE",
    name: "Roundhill Photonics & Optics ETF",
    shortName: "Optical Comp.",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "KWEB",
    name: "KraneShares CSI China Internet ETF",
    shortName: "China Internet",
    sector: "Technology",
    sectorKey: "technology",
    macroProfile: "ciclico",
    theme: "Cíclico",
  },
  {
    ticker: "XLU",
    name: "Utilities Select Sector SPDR Fund",
    shortName: "Utilities Sector",
    sector: "Utilities",
    sectorKey: "utilities",
    macroProfile: "defensivo",
    theme: "Defensivo",
  },
];

export const INDEX_TICKERS = BENCHMARKS.map((item) => item.ticker);

export const ALL_QUOTE_TICKERS = [
  ...INDEX_TICKERS,
  ...ETF_CATALOG.map((item) => item.ticker),
];
